services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8096:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=https://quotes.alejoforero.com/api









