services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8096:80"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - VITE_API_URL=${API_URL:-https://quotesfastapi.alejoforero.com/api}
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ./backend-python
      dockerfile: Dockerfile
    ports:
      - "8097:8000"
    environment:
      - PORT=8000
      - NODE_ENV=${NODE_ENV:-production}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-https://quotesfastapi.alejoforero.com}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
