services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8096:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${API_URL:-https://quotesfastapi.alejoforero.com/api}  # Make sure /api is included
  

  backend:
    build:
      context: ./backend-python
      dockerfile: Dockerfile
    ports:
      - "8097:8000"
    environment:
      - PORT=8000
      - NODE_ENV=${NODE_ENV:-production}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-https://quotesfastapi.alejoforero.com}
 
