services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8097:8000"
    environment:
      - PORT=8000
      - NODE_ENV=${NODE_ENV:-production}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-https://quotesfastapi.alejoforero.com}